### ISSUE TITLE
Lightdm slick greeter configuration failure

### ISSUE THREAD

**Issue by DeltaCopy** [arcolinux/archlinux-tweak-tool-dev#5]
Configured Slick greeter using ATT, resulted in 
![Screenshot_20230719_122655](https://github.com/arcolinux/archlinux-tweak-tool-dev/assets/121581829/dd86c145-99f5-40a9-925b-1a6114b9b23f)

This happens when Lightdm is already configured to use an existing greeter-session.

There is a bug which results in ATT adding the line `greeter-session=lightdm-slick-greeter` to the very first line of `/etc/lightdm/lightdm.conf`
Further investigation and eventual fix required in `functions.py`

**Comment by arcolinuxz** [comment]
installed and tested
all fine
thanks for the assist @DeltaCopy

**Comment by arcolinuxz** [comment]
Can you test once more?
Then I will move the code the actual ATT (now in dev)

**Comment by DeltaCopy** [comment]
@erikdubois 

This is the scenario I tested on Plasma, Xfce and Gnome.

- Installed LightDM
- Installed lightdm-webkit2-greeter
- Checked `/etc/lightdm/lightdm.conf` - make sure we have the following:

`[Seat:*]`
`greeter-session=lightdm-webkit2-greeter`

- Used ATT to install/enable slick-greeter
- Checked `/etc/lightdm/lightdm.conf`

Now see the following:

`[Seat:*]`
`greeter-session=lightdm-slick-greeter`
`#greeter-session=lightdm-webkit2-greeter`

The existing greeter-session is commented out.

Reboot. Validated that slick-greeter is now active.

Now validate removal of slick-greeter:

- Used ATT to remove slick-greeter
- Checked `/etc/lightdm/lightdm.conf`

Now see the following:

`[Seat:*]`
`greeter-session=lightdm-webkit2-greeter`

This shows that slick-greeter is removed from the conf file and the previous greeter is re-activated.

Reboot. Validated that webkit2-greeter is now active.
